# Generated by Django 3.1.6 on 2022-06-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='description',
            field=models.CharField(blank=True, help_text='длина до 200 символов (в идеале до 160)', max_length=200, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='title',
            field=models.CharField(help_text='Длина до 80 символов (в идеале на менее 40 и не более 70), заполнять обязательно', max_length=80, verbose_name='SEO Title'),
        ),
    ]
