# Generated by Django 3.1.6 on 2022-06-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220614_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='Изображение поста'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='text',
            field=models.TextField(blank=True, help_text='Основной текст страницы, количество символов не ограничено', verbose_name='Основной текст страницы'),
        ),
    ]
