# Generated by Django 3.1.6 on 2022-06-16 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Длина до 70 символов (в идеале на менее 40 и не более 70), заполнять обязательно', max_length=70, verbose_name='Название группы товаров')),
                ('image', models.ImageField(help_text='желательно 480х480, качество для web', upload_to='group/', verbose_name='Изображение группы товаров')),
            ],
            options={
                'verbose_name': ('Группы товаров',),
                'verbose_name_plural': 'Группы товаров',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Длина до 70 символов (в идеале на менее 40 и не более 70), заполнять обязательно', max_length=70, verbose_name='Название товара')),
                ('seo_title', models.TextField(help_text='Длина до 70 символов (в идеале на менее 40 и не более 70), заполнять обязательно', max_length=70, verbose_name='seo_title товара')),
                ('seo_description', models.TextField(help_text='Длина до 160 символов (в идеале на менее 40 и не более 160), заполнять обязательно', max_length=160, verbose_name='seo_description товара')),
                ('mini_description', models.TextField(help_text='Длина до 160 символов (в идеале на менее 40 и не более 160), заполнять обязательно', max_length=160, verbose_name='Краткое описание товара')),
                ('image', models.ImageField(blank=True, help_text='Изображение товара для главной страницы', null=True, upload_to='group/products/', verbose_name='Изображение товара 1')),
                ('description_first', models.TextField(blank=True, help_text='Полное описание товара - часть 1', null=True, verbose_name='Полное описание товара - часть 1')),
                ('description_second', models.TextField(blank=True, help_text='Полное описание товара - часть 2', null=True, verbose_name='Полное описание товара - часть 2')),
                ('image_description_first', models.ImageField(blank=True, help_text='Изображение товара для части описания 1', null=True, upload_to='group/products/', verbose_name='Изображение товара 2')),
                ('image_description_second', models.ImageField(blank=True, help_text='Изображение товара для части описания 2', null=True, upload_to='group/products/', verbose_name='Изображение товара 3')),
                ('characteristic', models.TextField(blank=True, help_text='Характеристики', null=True, verbose_name='Характеристики')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_products', to='products.groups', verbose_name='Группа товара')),
            ],
            options={
                'verbose_name': ('Товары',),
                'verbose_name_plural': 'Товары',
                'ordering': ('-pub_date',),
            },
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
