# Generated by Django 3.1.6 on 2022-06-14 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название группы товаров')),
                ('image', models.ImageField(upload_to='group/', verbose_name='Изображение группы товаров')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='group/products/', verbose_name='Изображение товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_products', to='products.groups')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
