# Generated by Django 3.1.6 on 2022-06-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': ('Группы товаров',), 'verbose_name_plural': 'Группы товаров'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-pub_date',), 'verbose_name': ('Товары',), 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(help_text='желательно 480х480, качество для web', upload_to='group/', verbose_name='Изображение группы товаров'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='title',
            field=models.CharField(help_text='Длина до 70 символов (в идеале на менее 40 и не более 70), заполнять обязательно', max_length=70, verbose_name='Название группы товаров'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(help_text='Длина до 300 символов (в идеале на менее 40 и не более 160), заполнять обязательно', max_length=300, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_products', to='products.groups', verbose_name='Группа товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='Длина до 70 символов (в идеале на менее 40 и не более 70), заполнять обязательно', max_length=70, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
