# Generated by Django 3.1.6 on 2022-06-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='slug',
        ),
    ]
