# Generated by Django 3.1.6 on 2022-06-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=10, help_text='Длина до 160 символов (в идеале на менее 40 и не более 160), заполнять обязательно', max_length=160, verbose_name='Основное описание товара'),
            preserve_default=False,
        ),
    ]
