# Generated by Django 3.1.6 on 2022-06-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='recipes',
            new_name='products',
        ),
    ]
