# Generated by Django 3.1.6 on 2022-06-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220610_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='group',
            new_name='groups',
        ),
    ]
