# Generated by Django 3.1.6 on 2022-06-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220614_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group/products/', verbose_name='Изображение товара'),
        ),
    ]
