# Generated by Django 3.1.6 on 2022-06-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='alt_image',
            field=models.TextField(default=1200, help_text='Длина до 160 символов (в идеале на менее 40 и не более 160), заполнять обязательно', max_length=160, verbose_name='Описание изображения для SEO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='alt_image_characteristic',
            field=models.TextField(default=1200, help_text='Длина до 160 символов (в идеале на менее 40 и не более 160), заполнять обязательно', max_length=160, verbose_name='Описание изображения для SEO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='alt_image_description_first',
            field=models.TextField(default=1200, help_text='Длина до 160 символов (в идеале на менее 40 и не более 160), заполнять обязательно', max_length=160, verbose_name='Описание изображения для SEO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='alt_image_description_second',
            field=models.TextField(default=1200, help_text='Длина до 160 символов (в идеале на менее 40 и не более 160), заполнять обязательно', max_length=160, verbose_name='Описание изображения для SEO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image_characteristic',
            field=models.ImageField(blank=True, help_text='Изображение товара для Характеристики', null=True, upload_to='group/products/', verbose_name='Изображение товара 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(blank=True, default='уточните у менеджера', null=True, verbose_name='Цена'),
        ),
    ]
