# Generated by Django 3.1.6 on 2022-06-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220616_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AlterField(
            model_name='products',
            name='alt_image_characteristic',
            field=models.TextField(blank=True, help_text='Длина до 160 символов (в идеале на менее 40 и не более 160), заполнять обязательно', max_length=160, null=True, verbose_name='Описание изображения для SEO'),
        ),
    ]
